### ISSUE TITLE
videosort renaming moves as TV shows

### ISSUE THREAD

**Issue by ghallford** [nzbget/VideoSort#12]
It did this with 3 movies. Renamed them as TV shows. Here are some example logs:

INFO    Wed Sep 21 2016 21:36:27    Post-process-script videosort\VideoSort.py for Talladega.Nights.2006.BluRay.720p.H264-20-40 successful
INFO    Wed Sep 21 2016 21:36:27    VideoSort: Deleted: \192.168.2.15\BT\DownloadedMovies\Talladega.Nights.2006.BluRay.720p.H264-20-40
INFO    Wed Sep 21 2016 21:36:27    VideoSort: Deleted: \192.168.2.15\BT\DownloadedMovies\Talladega.Nights.2006.BluRay.720p.H264-20-40\Talladega.Nights.2006.BluRay.720p.H264.jpg
INFO    Wed Sep 21 2016 21:36:27    VideoSort: Deleted: \192.168.2.15\BT\DownloadedMovies\Talladega.Nights.2006.BluRay.720p.H264-20-40\Talladega.Nights.2006.BluRay.720p.H264.nfo
INFO    Wed Sep 21 2016 21:36:27    VideoSort: Deleted: \192.168.2.15\BT\DownloadedMovies\Talladega.Nights.2006.BluRay.720p.H264-20-40\20-40.txt
INFO    Wed Sep 21 2016 21:36:27    VideoSort: Cleanup
INFO    Wed Sep 21 2016 21:36:27    VideoSort: Move satellites for \192.168.2.15\BT\DownloadedMovies\Talladega.Nights.2006.BluRay.720p.H264-20-40\Talladega.Nights.2006.BluRay.720p.H264.mp4
INFO    Wed Sep 21 2016 21:36:27    VideoSort: Moved: \192.168.2.15\BT\nzbget\dst/series\Talladega Nights 2006\Season 1\Talladega Nights 2006 - S01E40.mp4
INFO    Wed Sep 21 2016 21:36:27    VideoSort: destination path: \192.168.2.15\BT\nzbget\dst/series\Talladega Nights 2006\Season 1\Talladega Nights 2006 - S01E40.mp4
INFO    Wed Sep 21 2016 21:36:27    VideoSort: path after cleanup: Talladega Nights 2006\Season 1\Talladega Nights 2006 - S01E40.mp4
INFO    Wed Sep 21 2016 21:36:27    VideoSort: path after subst: Talladega Nights 2006/Season 1/Talladega Nights 2006 - S01E40 - ..mp4
INFO    Wed Sep 21 2016 21:36:27    VideoSort: format: %sn/Season %s/%sn - S%0sE%0e - %en.%ext
INFO    Wed Sep 21 2016 21:36:27    VideoSort: }
INFO    Wed Sep 21 2016 21:36:27    VideoSort: [1.00] "type": "episode"
INFO    Wed Sep 21 2016 21:36:27    VideoSort: [1.00] "season": 1,
INFO    Wed Sep 21 2016 21:36:27    VideoSort: [1.00] "screenSize": "720p",
INFO    Wed Sep 21 2016 21:36:27    VideoSort: [1.00] "vtype": "series",
INFO    Wed Sep 21 2016 21:36:27    VideoSort: [1.00] "year": 2006,
INFO    Wed Sep 21 2016 21:36:27    VideoSort: [0.70] "series": "Talladega Nights 2006",
INFO    Wed Sep 21 2016 21:36:27    VideoSort: [1.00] "format": "BluRay",
INFO    Wed Sep 21 2016 21:36:27    VideoSort: [1.00] "container": "mp4",
INFO    Wed Sep 21 2016 21:36:27    VideoSort: [1.00] "videoCodec": "h264",
INFO    Wed Sep 21 2016 21:36:27    VideoSort: ],
INFO    Wed Sep 21 2016 21:36:27    VideoSort: "20"
INFO    Wed Sep 21 2016 21:36:27    VideoSort: [1.00] "unidentified": [
INFO    Wed Sep 21 2016 21:36:27    VideoSort: [0.40] "episodeNumber": 40,
INFO    Wed Sep 21 2016 21:36:27    VideoSort: [1.00] "mimetype": "video/mp4",
INFO    Wed Sep 21 2016 21:36:27    VideoSort: {
INFO    Wed Sep 21 2016 21:36:27    VideoSort: Type: series
INFO    Wed Sep 21 2016 21:36:27    VideoSort: year is part of title
INFO    Wed Sep 21 2016 21:36:27    VideoSort: force season 1
INFO    Wed Sep 21 2016 21:36:27    VideoSort: }
INFO    Wed Sep 21 2016 21:36:27    VideoSort: [1.00] "type": "episode"
INFO    Wed Sep 21 2016 21:36:27    VideoSort: [1.00] "year": 2006,
INFO    Wed Sep 21 2016 21:36:27    VideoSort: [1.00] "screenSize": "720p",
INFO    Wed Sep 21 2016 21:36:27    VideoSort: [0.70] "series": "Talladega Nights",
INFO    Wed Sep 21 2016 21:36:27    VideoSort: [1.00] "format": "BluRay",
INFO    Wed Sep 21 2016 21:36:27    VideoSort: [1.00] "container": "mp4",
INFO    Wed Sep 21 2016 21:36:27    VideoSort: [1.00] "videoCodec": "h264",
INFO    Wed Sep 21 2016 21:36:27    VideoSort: ],
INFO    Wed Sep 21 2016 21:36:27    VideoSort: "20"
INFO    Wed Sep 21 2016 21:36:27    VideoSort: [1.00] "unidentified": [
INFO    Wed Sep 21 2016 21:36:27    VideoSort: [0.40] "episodeNumber": 40,
INFO    Wed Sep 21 2016 21:36:27    VideoSort: [1.00] "mimetype": "video/mp4",
INFO    Wed Sep 21 2016 21:36:27    VideoSort: {
INFO    Wed Sep 21 2016 21:36:27    VideoSort: {u'container': u'mp4'}
INFO    Wed Sep 21 2016 21:36:27    VideoSort: {u'mimetype': u'video/mp4', u'container': u'mp4'}
INFO    Wed Sep 21 2016 21:36:27    VideoSort: {u'episodeNumber': 40}
INFO    Wed Sep 21 2016 21:36:27    VideoSort: {u'videoCodec': u'h264'}
INFO    Wed Sep 21 2016 21:36:27    VideoSort: {u'screenSize': u'720p'}
INFO    Wed Sep 21 2016 21:36:27    VideoSort: {u'format': u'BluRay'}
INFO    Wed Sep 21 2016 21:36:27    VideoSort: {u'year': 2006}
INFO    Wed Sep 21 2016 21:36:27    VideoSort: {u'series': u'Talladega Nights'}
INFO    Wed Sep 21 2016 21:36:27    VideoSort: {u'type': u'episode'}
INFO    Wed Sep 21 2016 21:36:27    VideoSort: Talladega.Nights.2006.BluRay.720p.H264-20-40.mp4
INFO    Wed Sep 21 2016 21:36:27    VideoSort: TTTTTTTTTTTTTTTTTyyyy ffffff ssss vvvv EE ccc
INFO    Wed Sep 21 2016 21:36:27    VideoSort: _____________________.______.____.____-20-**._**
INFO    Wed Sep 21 2016 21:36:27    VideoSort: 000011
INFO    Wed Sep 21 2016 21:36:27    VideoSort: 01111222222
INFO    Wed Sep 21 2016 21:36:27    VideoSort: 0000000000000000011112 0111122222222222
INFO    Wed Sep 21 2016 21:36:27    VideoSort: 00000000000000000000001111112222222222222222 000
INFO    Wed Sep 21 2016 21:36:27    VideoSort: 00000000000000000000000000000000000000000000 000
INFO    Wed Sep 21 2016 21:36:27    VideoSort: 00000000000000000000000000000000000000000000 111
INFO    Wed Sep 21 2016 21:36:27    VideoSort: Guessing: Talladega.Nights.2006.BluRay.720p.H264-20-40.mp4
INFO    Wed Sep 21 2016 21:36:27    VideoSort: Using NZB-Name
INFO    Wed Sep 21 2016 21:36:27    VideoSort: filename: \192.168.2.15\BT\DownloadedMovies\Talladega.Nights.2006.BluRay.720p.H264-20-40\Talladega.Nights.2006.BluRay.720p.H264.mp4
INFO    Wed Sep 21 2016 21:36:24    Executing post-process-script videosort\VideoSort.py for Talladega.Nights.2006.BluRay.720p.H264-20-40

**Comment by cxhamilton** [comment]
VideoSort uses [guessit](https://github.com/guessit-io/guessit) to parse and obtain information about a media file. This shows how guessit parsed the title (note the "EE").

```
INFO Wed Sep 21 2016 21:36:27 VideoSort: Talladega.Nights.2006.BluRay.720p.H264-20-40.mp4
INFO Wed Sep 21 2016 21:36:27 VideoSort: TTTTTTTTTTTTTTTTTyyyy ffffff ssss vvvv EE ccc
```

This confirms that [guessit](https://github.com/guessit-io/guessit) believes that the media file is episode 40 of a series.

```
INFO Wed Sep 21 2016 21:36:27 VideoSort: [1.00] "type": "episode"
...
INFO Wed Sep 21 2016 21:36:27 VideoSort: [1.00] "vtype": "series",
...
INFO Wed Sep 21 2016 21:36:27 VideoSort: [0.40] "episodeNumber": 40,
```

@hugbug Apologies if I speak out of turn, but this is not a problem that VideoSort should solve for. It would be best to open an issue with the [guessit](https://github.com/guessit-io/guessit) project and VideoSort can update its bundled version afterward.

**Comment by hugbug** [comment]
Yes but first we need to update our guessit version, which is two years old. Looking at guessit site I see that in the meantime it was completely rewritten from scratch, it lives in a different github repository, and the author is a different developer, the API was redesigned (incompatible). So basically an all new library from a different developer although probably approved by the original author.

**Comment by Zareba** [comment]
It would be really awesome if guessit is update to a newer version.

**Comment by hugbug** [comment]
After upgrading guessit (see #20) this issue is fixed as guessit2 correctly identifies "20-40" as release group.

**Comment by fernandog** [comment]
It means 20-40 mbps, not release group.
Medusa team just found out this guessit issue and we will open issue there

**Comment by hugbug** [comment]
20-40 is a release group name.
