### ISSUE TITLE
Skip rename if media file is already named correctly

### ISSUE THREAD

**Issue by Kalroth** [nzbget/VideoSort#13]
The directory (NZB?) name is always the correct one for me, while its rarely correct for the filename. So I use the following pattern to rename movie files: `%dn/%dn.%ext`

My issue is that if the file is already named correctly, it gets renamed to Movie.2017-RLS (2).mkv.

I've tried to enable overwrite, but that only makes VideoSort throw the download away and NZBGet then starts downloading the media again.

Is there a way to avoid renaming movie files that are already named correctly?

**Comment by hugbug** [comment]
Fixed with #17.
