### ISSUE TITLE
Script compatibility for Sabnzbd

### ISSUE THREAD

**Issue by kapps7** [nzbget/VideoSort#14]
Hi,
Would you expect this to work with Sabnzbd ?
Thanks

**Comment by hugbug** [comment]
No and you don't need this as SAB has a built-in sorting.

**Comment by kapps7** [comment]
Really. I found your script very useful on NZBget. Ok I'll look around in Sab - never had the same results from default settings in SAB as your script.

**Comment by hugbug** [comment]
Let me close this then.
Feel free to reopen if you have further question.

**Comment by kapps7** [comment]
Andrey, sorry one quick question: Is it possible to use your script as a service on Mac OS or run in on a library folder

**Comment by hugbug** [comment]
Currently the script works only in NZBGet post-processing context. It is surely possible to modify it to run directly from terminal on a specified directory, which it would process but this change should make someone else. I'll accept a merge request.
