### ISSUE TITLE
Installed and scan incoming does not work or local download

### ISSUE THREAD

**Issue by mistercorea** [nzbget/VideoSort#15]
I have installed the binary version on my mac.
everything is default configuration and installed videosort plugin, changed the minimum mega bytes to 0.

Enabled the extension and I have downloaded the The.Big.Bang.Theory.S10E21.720p.HDTV.X264-DIMENSION.mkv from localhost.
it goes to ~/Library/Application Support/NZBGet/nzb and it's not creating or moving the files to series/x/y.mkv

is there anyway i can just run the post script?
EDIT:
When I run post process from history page it doesn't run anything.
the status is skipped and error message "Cannot post-process URL- or hidden records"

**Comment by hugbug** [comment]
The script must be selected fo nzb. Add new nzb, then click on it in download list , then button Postprocess. Make sure Videosort is selected.

**Comment by mistercorea** [comment]
Extensions are selected 
"Logger.py, VideoSort/VideoSort.py"
but still not post processing.

**Comment by mistercorea** [comment]
`MainDir=~/Library/Application Support/NZBGet
DestDir=~/Downloads
InterDir=~/Downloads/Intermediate
NzbDir=${MainDir}/nzb
QueueDir=${MainDir}/queue
TempDir=${MainDir}/tmp
ScriptDir=${MainDir}/scripts
LogFile=~/Library/Logs/NZBGet.log
RequiredDir=
Server1.Active=yes
Server1.Name=
Server1.Level=0
Server1.Optional=no
Server1.Group=0
Server1.Host=my.newsserver.com
Server1.Port=119
Server1.Username=user
Server1.Password=pass
Server1.JoinGroup=no
Server1.Encryption=no
Server1.Cipher=
Server1.Connections=4
Server1.Retention=0
ControlIP=0.0.0.0
ControlPort=6789
ControlUsername=nzbget
ControlPassword=tegbzn6789
RestrictedUsername=
RestrictedPassword=
AddUsername=
AddPassword=
SecureControl=no
SecurePort=6791
SecureCert=
SecureKey=
AuthorizedIP=127.0.0.1
UMask=1000
Category1.Name=Movies
Category1.DestDir=
Category1.Unpack=yes
Category1.Extensions=
Category1.Aliases=
Category2.Name=Series
Category3.Name=Music
Category4.Name=Software
AppendCategoryDir=yes
NzbDirInterval=5
NzbDirFileAge=60
DupeCheck=yes
SaveQueue=yes
FlushQueue=yes
ReloadQueue=yes
ContinuePartial=yes
PropagationDelay=0
Decode=yes
ArticleCache=700
DirectWrite=no
WriteBuffer=1024
CrcCheck=yes
PostStrategy=balanced
DiskSpace=250
NzbCleanupDisk=yes
KeepHistory=30
FeedHistory=7
ArticleRetries=3
ArticleInterval=10
ArticleTimeout=60
UrlRetries=3
UrlInterval=10
UrlTimeout=60
TerminateTimeout=600
DownloadRate=0
AccurateRate=no
UrlConnections=4
UrlForce=yes
MonthlyQuota=0
QuotaStartDay=1
DailyQuota=0
WriteLog=append
RotateLog=3
ErrorTarget=both
WarningTarget=both
InfoTarget=both
DetailTarget=log
DebugTarget=log
LogBufferSize=1000
NzbLog=yes
BrokenLog=yes
DumpCore=no
TimeCorrection=0
OutputMode=curses
CursesNzbName=yes
CursesGroup=no
CursesTime=no
UpdateInterval=200
ParCheck=auto
ParRepair=yes
ParScan=extended
ParQuick=yes
ParBuffer=500
ParThreads=0
ParIgnoreExt=.sfv, .nzb, .nfo
ParRename=yes
RarRename=yes
HealthCheck=park
ParTimeLimit=0
ParPauseQueue=no
Unpack=yes
UnpackPauseQueue=no
UnpackCleanupDisk=yes
UnrarCmd=${AppDir}/unrar
SevenZipCmd=${AppDir}/7zr
ExtCleanupDisk=.par2, .sfv, _brokenlog.txt
UnpackIgnoreExt=.cbr
UnpackPassFile=
Extensions=Logger.py, VideoSort/VideoSort.py
ScriptOrder=
ScriptPauseQueue=no
ShellOverride=
EventInterval=0
Category2.DestDir=
Category2.Unpack=yes
Category2.Extensions=
Category2.Aliases=
Category3.DestDir=
Category3.Unpack=yes
Category3.Extensions=
Category3.Aliases=
Category4.DestDir=
Category4.Unpack=yes
Category4.Extensions=
Category4.Aliases=
EMail.py:SendMail=Always
EMail.py:From="NZBGet" <myaccount@gmail.com>
EMail.py:To=myaccount@gmail.com
EMail.py:Server=smtp.gmail.com
EMail.py:Port=25
EMail.py:Encryption=yes
EMail.py:Username=myaccount
EMail.py:Password=mypass
EMail.py:Statistics=yes
EMail.py:FileList=yes
EMail.py:BrokenLog=yes
EMail.py:NzbLog=OnFailure
VideoSort/VideoSort.py:MoviesDir=${DestDir}/movies
VideoSort/VideoSort.py:SeriesDir=${DestDir}/series
VideoSort/VideoSort.py:DatedDir=${DestDir}/tv
VideoSort/VideoSort.py:OtherTvDir=${DestDir}/tv
VideoSort/VideoSort.py:TvCategories=tv
VideoSort/VideoSort.py:VideoExtensions=.mkv,.avi,.divx,.xvid,.mov,.wmv,.mp4,.mpg,.mpeg,.vob,.iso
VideoSort/VideoSort.py:SatelliteExtensions=.srt,.sub
VideoSort/VideoSort.py:MinSize=0
VideoSort/VideoSort.py:MoviesFormat=%t (%y)
VideoSort/VideoSort.py:SeriesFormat=%sn/Season %s/%sn - S%0sE%0e - %en
VideoSort/VideoSort.py:EpisodeSeparator=E
VideoSort/VideoSort.py:SeriesYear=yes
VideoSort/VideoSort.py:DatedFormat=%sn/%sn - %y-%0m-%0d
VideoSort/VideoSort.py:OtherTvFormat=%t
VideoSort/VideoSort.py:LowerWords=the,of,and,at,vs,a,an,but,nor,for,on,so,yet
VideoSort/VideoSort.py:UpperWords=III,II,IV
VideoSort/VideoSort.py:DNZBHeaders=yes
VideoSort/VideoSort.py:PreferNZBName=no
VideoSort/VideoSort.py:Overwrite=no
VideoSort/VideoSort.py:Cleanup=yes
VideoSort/VideoSort.py:Preview=yes
VideoSort/VideoSort.py:Verbose=yes`

**Comment by hugbug** [comment]
Add new nzb, then click on it in download list , then button Postprocess. Make sure Videosort is selected.

**Comment by mistercorea** [comment]
http://localhost:6789/#DownloadsTab
->
Add new link
-> 
Downloaded
->
History page nothing happened.

**Comment by mistercorea** [comment]
http://localhost:6789/#EXTENSION_SCRIPTS 
the very first option extensions videoSort.py is choosen.

**Comment by mistercorea** [comment]
There is no wiki page or a documentation for how to get it up.

**Comment by hugbug** [comment]
It's hard to help if you don't follow my instructions:

> Add new nzb, then click on it in download list , then button Postprocess. Make sure Videosort is selected.

We can try the other way. Click on history item, make a screenshot and post it. Then click on button "Log", then button "Save to log", post the log via pastebin.com.

**Comment by mistercorea** [comment]
![screen shot 2017-04-12 at 12 04 58 pm](https://cloud.githubusercontent.com/assets/2279899/24970201/0f187bcc-1f79-11e7-90c0-94723494b0cf.png)
![screen shot 2017-04-12 at 12 04 35 pm](https://cloud.githubusercontent.com/assets/2279899/24970202/0f1d31ee-1f79-11e7-9746-7a0317d052b8.png)
![screen shot 2017-04-12 at 12 04 21 pm](https://cloud.githubusercontent.com/assets/2279899/24970200/0f1863f8-1f79-11e7-9bd9-1fe0281c1068.png)

**Comment by mistercorea** [comment]
There is no post process button on the downloads tab.
![screen shot 2017-04-12 at 12 11 51 pm](https://cloud.githubusercontent.com/assets/2279899/24970249/44a915bc-1f79-11e7-8fb8-62ed53e883f3.png)

I have nzbget 18.1 lightweight usenet download  if this information helps.

**Comment by hugbug** [comment]
Do you know what Usenet is and what are nzb-files?
Because it looks like you have no idea.
VideoSort is a post-processing script for files downloaded with NZBGet. If your intention was to organize existing video files, then VideoSort can't do that and you need another tool.

**Comment by mistercorea** [comment]
SIGH. okay now it make sense. 
I thought nzbget was like a download file manager. not a nzb(torrent like) client.
