### ISSUE TITLE
Videosort.py:ImportError: /opt/lib/python2.7/lib-dynload/_collections.so: wrong ELF class: ELFCLASS32

### ISSUE THREAD

**Issue by reimgun** [nzbget/VideoSort#18]
Hi,

i have the following setup:
QNAP TS451
python 2.7.12
NZBGet 18.1
latest Videosort: https://github.com/nzbget/VideoSort
i have updated my Qnap TS451 to 4.3.3 

I facing now the following issue: 

nzbToMedia/VideoSort.py: ImportError: /opt/lib/python2.7/lib-dynload/_collections.so: wrong ELF class: ELFCLASS32
nzbToMedia/VideoSort.py: from _collections import deque, defaultdict
nzbToMedia/VideoSort.py: File "/opt/lib/python2.7/collections.py", line 8, in <module>
nzbToMedia/VideoSort.py: import collections
nzbToMedia/VideoSort.py: File "/opt/lib/python2.7/shutil.py", line 12, in <module>
nzbToMedia/VideoSort.py: import shutil
nzbToMedia/VideoSort.py: File "/share/CACHEDEV1_DATA/.qpkg/NZBGet/nzbget/scripts/nzbToMedia/VideoSort.py", line 260, in <module>

any Ideas?

regards
guenther

**Comment by hugbug** [comment]
Something is wrong with your python installation.

As this is not a bug in VideoSort there is unfortunately nothing I can do to help you with the issue.

Try asking on QNAP forum. Others should have similar issues with python programs (not necessary VideoSort) and may already have a solution.

**Comment by raucous** [comment]
I am having a similar issue. Could it be that I am running 64bit architecture and VideoSort is trying to pull a 32bit library?

**Comment by hugbug** [comment]
VideoSort is a pure python thing. It doesn't know anything about 32 or 64 bits. The error means that there is something wrong with your python installation.
