### ISSUE TITLE
videosort fails in post with path error on Fedora 26

### ISSUE THREAD

**Issue by khuffmanjr** [nzbget/VideoSort#27]
Hello!  I have been using videosort with nzbget for more than a year on Ubuntu MATE.  Love it!  Would like to move to a new VM for reasons.  Fedora 26 wasn't a good choice, apparently.  While nzbget runs well my videosort script failed in post with message:  "VideoSort: /usr/bin/env: ‘python’: No such file or directory"

I am now building a CentOS 7 VM for the same, as CentOS is the original OS I wanted to use, but I wanted to raise the issue in case this helps me succeed with CentOS or maybe it'll help with others trying this on Fedora 26 or similar.

Anyone seen this or know what I can do to make this work?

Thanks!

**Comment by hugbug** [comment]
Apparently "python" is not in your PATH. Either make command "python" work (in terminal) or put the whole path to python into first line of the script, google "shebang" for more info.

**Comment by khuffmanjr** [comment]
Well, I'm lost.  I tried setting `#! /usr/bin/env python3` but then the script fails with syntax error. I also tried the standard shebang but this time linking python to python3.  It failed with the same error.  So I guess its python.  I only have python3 on this machine so maybe that's the problem?

**Comment by hugbug** [comment]
VideoSort requires python2 and isn't compatible with python3. You need to install python2 (both pyhtons can coexist). Then, if you still have troubles with launching correct python - use option ShellOverride in nzbget.

**Comment by khuffmanjr** [comment]
I've installed python2.6 and recovered my videosort capability.  Thanks much!
