### ISSUE TITLE
Ability to keep original content in download directory after re-processing

### ISSUE THREAD

**Issue by saghassy** [nzbget/VideoSort#28]
I usually like to keep the content back in the download directory after re-processing so I can see that there is new stuff. I am just switching over from Sickbeard, which has this ability. Can we add this to VideoSort as well? I am a software engineer, but am not too familiar with the project, I went ahead and wrote a crappy implementation of this and attached it here. The directory structure is a bit confusing since it seems nzbget moves tv shows to a 'series' subfolder first, then does post-processing? So moving it back to parent directory was a bit weird. 
Please let me know if you think this feature is worth adding. If it is, feel free to implement yourself and ignore my changes.

[VideoSort.zip](https://github.com/nzbget/VideoSort/files/1290847/VideoSort.zip)

**Comment by saghassy** [comment]
Here is a diff that this would produce 
https://github.com/saghassy/VideoSort/commit/1cb7ce60e2b85823000363193c98818d328c6587#diff-e1bc038850034289a7dffdb96d1ef9cf
created on my branch.

**Comment by hugbug** [comment]
I see how copying can be an alternative to moving but the move-back function shouldn't be necessary.

>nzbget moves tv shows to a 'series' subfolder

If you tell it to. By defaul nzbget creates subdirectory with category name. If you don't need it you can either disable option "AppendCategoryDir" or by defining an explicit destination path for directory.

**Comment by saghassy** [comment]
Ahhhh thanks. I thought there would be a setting for this, looks like it was in a place I didn't look! Thanks for the quick response.

One more question... does VideoSort not lookup episode names from thetvdb.com similar to sickbeard post processing? So far, all of the renames that it has done for me come up with no episode name.

**Comment by hugbug** [comment]
> does VideoSort not lookup episode names from thetvdb.com

No. It can use episode names parsed from filenames or if they were sent by indexer when nzb-file was fetched from indexer by nzbget. I don't know how many indexers push this info though but at least dog does.

An issue with pulling data from thetvdb.com is that it's hard to identity show properly as there are a lot of shows with same names from different years etc.

If you want to add this functionality I'd be happy to merge.

----

Regarding the theme of this issue (keep original content): would you make a **pull request** from your branch? I mean after removing the unnecessary move-back part.

**Comment by hugbug** [comment]
Closing this due to a lack of feedback.
Feel free to post to thread if you want it to be reopened.
