### ISSUE TITLE
Error - VideoSort: 'module' object has no attribute 'patterns'

### ISSUE THREAD

**Issue by kalle-del-haye** [nzbget/VideoSort#30]
Almost any download show this error in the log:

> error Post-process-script VideoSort-master/VideoSort.py for *** failed
error VideoSort: 'module' object has no attribute 'patterns'
error VideoSort: Failed: ***.sub
info VideoSort: Moved: ***.mkv
info VideoSort: AttributeError: 'module' object has no attribute 'patterns'
info VideoSort: if fextlo[1:] in guessit.patterns.extension.subtitle_exts:
info VideoSort: File "/opt/nzbget/scripts/VideoSort-master/VideoSort.py", line 448, in move_satellites
info VideoSort: move_satellites(old_path, new_path)
info VideoSort: File "/opt/nzbget/scripts/VideoSort-master/VideoSort.py", line 1243, in <module>
info VideoSort: Traceback (most recent call last):
info Executing post-process-script VideoSort-master/VideoSort.py for ***

To my knowledge the call `guessit.patterns.extension.subtitle_exts` in line 448 isn't supported by the integrated GuessIT version in `/lib/guessit`? I've found the subtitle extensions in `/lib/guessit/rules/properties/container.py` but have no idea how to use them.

Maybe you can take a look on this problem?
Thanks.

**Comment by Kalroth** [comment]
This repository seems to be largely abandoned, so I fixed the above error in this commit:
https://github.com/Kalroth/VideoSort/commit/fd8569e9d22b55eb8e0f58751509f20f484b5e3b

I've only tested it with .sub, .idx and .nfo extensions so far, but that seems to work.

You can download the full release here:
https://github.com/Kalroth/VideoSort/releases/tag/v6.2

**Comment by hugbug** [comment]
@Kalroth, thanks for the fix.
It'd be great if you could create pull request.
I'll post a new release after that.

**Comment by Kalroth** [comment]
I've created a pull request here:
https://github.com/nzbget/VideoSort/pull/42

It fixes the guessit issues for me, but it's only been tested with about 30-40 downloads.

**Comment by Kalroth** [comment]
I've made the pull request here:
https://github.com/nzbget/VideoSort/pull/43

Now it should only contain the relevant changes.

**Comment by hugbug** [comment]
Thanks @Kalroth. Merged the fix.
