### ISSUE TITLE
TV show naming

### ISSUE THREAD

**Issue by Enzomatrix01** [nzbget/VideoSort#31]
I currently have two main directories for shows.  Anime and TV Shows.  

My setup consists of NZBGET with the latest version of Videosort.  I have also installed python 2.7.14.  I'm using Sonarr to call the tv series down and have the two catagories specified in NZBGET.   Until recently I had the catagory anime specified in Sonarr to download to the correct folder however I found that by using videosort it would default the file as a movie file and place it in another directory all together with the incorrect naming scheme.  

I corrected this by listing it as a tv show while keeping the directory specified in Sonarr,  however the naming is a problem with a specific series.  

Instead of the common season and episode naming they have decided to just name them by episode number,  (95,96,97,ect)  and while this can be deciphered using thetvdb.com videosort ignores it and forces a movie naming listing as other tv.    

I'm uploading log files of the process for this series and one of a regular show that is working.  The script is working perfectly for all other shows and movies with the exception of this one.   Any help would be appreciated.  

[Fear.the.Walking.Dead.S03E14.720p.HDTV.x264-FLEET.log](https://github.com/nzbget/VideoSort/files/1367625/Fear.the.Walking.Dead.S03E14.720p.HDTV.x264-FLEET.log)

[[HorribleSubs].Dragon.Ball.Super.-.106.[720p].log](https://github.com/nzbget/VideoSort/files/1367624/HorribleSubs.Dragon.Ball.Super.-.106.720p.log)

**Comment by hugbug** [comment]
VideoSort requires filenames having certain format as it extracts all infos from file names.
In particular Anime isn't handled well because of this. It's best to configure your system to not run VideoSort for that kind of content (use categories in nzbget and configure own extensions for that category, which do not include VideoSort). A fix on VideoSort isn't possible unfortunately.
