### ISSUE TITLE
Sonarr/Radarr Download Completion Handling integration

### ISSUE THREAD

**Issue by hechz** [nzbget/VideoSort#35]
I've noticed that completed downloads remain in the activity queue for these applications despite completion. Could a DELETE to the queue API of these applications be added as an option?

Here's an example in shell
<code shell>
for i in $(curl -k -H 'X-Api-Key:REDACTED' -H 'authority: sonarr.dom.tld' --compressed  'https://sonarr.dom.tld/api/queue' | jq '.[].id') ;do \
    echo "curl -k -X DELETE -H 'origin: https://sonarr.dom.tld'  -H 'referer: https://sonarr.dom.tld/activity/queue'  -H 'authority: sonarr.dom.tld'  -H 'X-Api-key: REDACTED' 'https://sonarr.dom.tld/api/queue/'$i'?blacklist=false'"; \
done \
| sh -xse

</code>

**Comment by hugbug** [comment]
Please create a separate script and run it after VideoSort. Integrating this directly into VideoSort doesn't make sense.

Perhaps you shouldn't use VideoSort at all and let Sonarr/Radarr rename your files.

**Comment by hechz** [comment]
Fair enough, but Sonarr and Radarr structuring didn’t work as automatically, have to go in and kick off an organize operation. 

VideoSort notifying the upstream application that called NZBGET makes sense IMHO, but fair enough

**Comment by hugbug** [comment]
> VideoSort notifying the upstream application that called NZBGET makes sense IMHO

Whether it's VideoSort notifying the other apps or **another script** (run after VideoSort) - the result for you is the same. NZBGet can run multiple post-processing scripts one after another.
