### ISSUE TITLE
I need an idiot's guide to install guessit

### ISSUE THREAD

**Issue by greebo34** [nzbget/VideoSort#37]
My videosort is failing because it cant find guessit.  Looking at the nzbget log.

Collection Black.S01E09.720p.HEVC.x265-MeGusta added to history
--
error | Wed Mar 21 2018 21:49:04 | Post-process-script  VideoSort\VideoSort.py for  Black.S01E09.720p.HEVC.x265-MeGusta failed (terminated with  unknown status)
info | Wed Mar 21 2018 21:49:04 | VideoSort: ImportError: No module named guessit
info | Wed Mar 21 2018 21:49:04 | VideoSort:     __import__(moduleOrReq)
info | Wed Mar 21 2018 21:49:04 | VideoSort:   File "C:\ProgramData\NZBGet\scripts\VideoSort/lib\pkg_resources.py", line 219, in get_provider
info | Wed Mar 21 2018 21:49:04 | VideoSort:     return get_provider(package_or_requirement).get_resource_stream(
info | Wed Mar 21 2018 21:49:04 | VideoSort:   File "C:\ProgramData\NZBGet\scripts\VideoSort/lib\pkg_resources.py", line 919, in resource_stream
info | Wed Mar 21 2018 21:49:04 | VideoSort:     for l in resource_stream('guessit', 'tlds-alpha-by-domain.txt').readlines()
info | Wed Mar 21 2018 21:49:04 | VideoSort:   File "C:\ProgramData\NZBGet\scripts\VideoSort/lib\guessit2\rules\properties\website.py", line 26, in website
info | Wed Mar 21 2018 21:49:04 | VideoSort:     rebulk.rebulk(website())

I installed nzbget, then python 2.7.14 (64bit), then pywin32 which confirmed the install of python 64bit.

But then I'm mystified what I do now?  
I tried launching python gui and typing $ pip install guessit but get a syntax error.

My apologies for my noob query.

Greebo

**Comment by hugbug** [comment]
Your VideoSort folder has subdirectory "lib\guessit2". You shouldn't have it.

The title page of github project (https://github.com/nzbget/VideoSort) contains section "Installation". Have you followed it?

You don't have to install guessit or anything else except Python (pywin32 isn't necessary as well).

**Comment by greebo34** [comment]
Thx very much for prompt reply.  All sorted, need my eyes tested.

G.
