### ISSUE TITLE
Radar incorrectly path for import

### ISSUE THREAD

**Issue by behold81** [nzbget/VideoSort#38]
So as files are getting more messed up I need videosort to ensure they are named right. 

But auto import fails. The file path sent to radarr is incorrect and can’t find the file. 

What is the fix???

**Comment by hugbug** [comment]
I don't understand what you mean. Does VideoSort renames files correctly?

**Comment by behold81** [comment]
Yes videosort renames the file perfectly. 

Then when radarr is importing it’s looking up the file not in the directory so failed to find it.

**Comment by hugbug** [comment]
>The file path sent to radarr

Neither nzbget nor VideoSort send anything to Radarr, they don't aware of Radarr and don't communicate with it.

If VideoSort moves files into another location (depends on settings) the new location is stored in property FinalDir of nzb history item. If Radarr doesn't use that information it its fall.

Perhaps you shouldn't use VideoSort at all, Radarr is supposed to do all the renaming on its own.

**Comment by behold81** [comment]
I’ll check the finaldir history. Where is this stored?  

Radarr fails to do the renaming quite often due to file name length or characters 

I just have to manual import. It’s just annoying that’s all. 

Must be a reason.

**Comment by hugbug** [comment]
For FinalDir see https://nzbget.net/api/history.
