### ISSUE TITLE
Cannot find VideoSort settings menu - using NZBGet 15

### ISSUE THREAD

**Issue by litfoo** [nzbget/VideoSort#4]
I have uploaded the .py file and lib folder to a videosort folder in my scripts folder.
![lhgoiuu - imgur](https://cloud.githubusercontent.com/assets/14896090/10177868/682ea054-66f4-11e5-89a0-db78feedb3c9.png)

However the VideoSort settings menu is not showing up in my NZBget 15 settings page.

![xz3c0y9](https://cloud.githubusercontent.com/assets/14896090/10177922/b4a6f166-66f4-11e5-9270-6a24667a1918.png)

Can someone see where I am going wrong

thanks in advance

litfoo

**Comment by hugbug** [comment]
What path is set in option **ScriptDir** (section PATHS)?

**Comment by litfoo** [comment]
Was /usr/local/nzbget/share/nzbget/ppscripts

Have now changed to /usr/local/nzbget/share/nzbget/scripts

Thanks for spotting.
