### ISSUE TITLE
New release fails

### ISSUE THREAD

**Issue by Isstum** [nzbget/VideoSort#44]
Using 8.0 and NZBget via Docker.

VideoSort fails, but i just got this error in the logs (verbose avtivated):

``VideoSort: sequence item 14: expected string or Unicode, list found
``
Any ideas?

**Comment by hugbug** [comment]
Is this the only message printed by VideoSort? You better post the whole log without stripping.

**Comment by Isstum** [comment]
Can i find any other logs than provided by nzbget?

**Comment by hugbug** [comment]
Click on item in history, then button Log, then button "Save to file". Post log here.

**Comment by Isstum** [comment]
Ah, sry. Just saw the lines marked as "Error" ;D


[nzbget.log](https://github.com/nzbget/VideoSort/files/2250724/nzbget.log)

**Comment by hugbug** [comment]
Try this:
- open settings page in nzbget
- click "save all settings" (even though you haven't changed any).

Now test if VideoSort works.

**Comment by Isstum** [comment]
Ok, that worked. Why? 
I saved the config before (enabling verbose mode).

**Comment by Isstum** [comment]
Thank you very much!

**Comment by Isstum** [comment]
Redownloaded the file. Got the same error. Maybe because it starts with a number?

Other files seem to work fine. Maybe this special file is corrupted in any way? 
Tried another file with a starting number. Still worked.

Thank you very much! Its working now :D
