### ISSUE TITLE
Movie title (original letter case) not working

### ISSUE THREAD

**Issue by rEes9P** [nzbget/VideoSort#49]
I think there may be a bug in the movie title (original letter case) naming convention. The notes mention "%tT, %t.T, %t_T" as the specifiers. However, using "%tT" for a movie, let's call it _Random_, results in the T being appended to the name such that the name becomes _RandomT_.

"%t" works just fine though.

**Comment by fleXible** [comment]
Hi,

I noticed the same, a couple of days age, when I was investigating an unrelated issue. I might open a PR in the next couple of days, as by fixing the one issue, I had to first cope with the other.

**Comment by fleXible** [comment]
Well, I'm afraid the issue needs to be reopened. Although the specifiers are correctly recognized and replaced now, they still do change the case.
The test case is actually testing the exact opposite behavior of what is documented:
- [Test case: %t_T - original letter case](https://github.com/nzbget/VideoSort/blob/e3e99000235736cfdb483f2f9a3faf6ba33d2da6/testdata.json#L45)

The correcting PR will follow soon.

**Comment by rEes9P** [comment]
Many thanks for the update. I must be having a brain freeze for I cannot remember how to update to the commit. Could you please explain to me how I may go about updating my VideoSort script? Thanks again!

**Comment by fleXible** [comment]
> Many thanks for the update. I must be having a brain freeze for I cannot remember how to update to the commit. Could you please explain to me how I may go about updating my VideoSort script? Thanks again!

Just download the updated [VideoSort.py](https://raw.githubusercontent.com/nzbget/VideoSort/master/VideoSort.py) script and replace it in your NZBGet installation. There you should find it under `bin/scripts`.
