### ISSUE TITLE
Dated show name (original letter case) not working (related to #49)

### ISSUE THREAD

**Issue by fleXible** [nzbget/VideoSort#52]
Because the code used in DatedFormat to create the show name specifiers is a copy of the buggy code leading to #49 they both share the issue but have to be fixed separately.

The current issues with DatedFormat are:
- **%sN, %s.N, %s_N** specifiers not working as expected
- empty **%desc, %.desc, %_desc**specifiers instead of episode specifiers are created. See #51 
- **%t, %.t, %_t** specifiers are created and even used in the tests, but undocumented and refer to movie title

Related issues with movie title (original letter case) specifiers:
- Because both were based on the same code, also the movie title specifiers for the original letter case are not working as documented
- #49 only fixed, they were not working at all

**Comment by hugbug** [comment]
Can this be closed now?

**Comment by fleXible** [comment]
Yes, finally!
